language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  
before_deploy:
  - zip -r jpatest *
  - mkdir -p deploy
  mv jpatest.zip deploy/jpatest.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY AKIAR7HM6G54OZ4HYRFR # Travis repo settings에 설정된 값
    access_key_key: $AWS_SECRET_KEY 8qBQIliZwD3YinrxcGUk9hblaVpEXDesg3eKAFj7 # Travis repo settings에 설정된 값
    bucket: springboot-test-build1 # S3 버킷
    region: ap-northeast-2 
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-untill-deployed: true
  

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - woals214@gmail.com